In [39]:
%pdb
import numpy as np
import pandas as pd
import ipywidgets as widgets



Automatic pdb calling has been turned OFF


### Which state you want to view

In [60]:
dropdown = widgets.Dropdown(
    options=['Chicago', 'New york city', 'Washington'],
    value='Chicago',
    description='States:'
)
dropdown

Dropdown(description='States:', options=('Chicago', 'New york city', 'Washington'), value='Chicago')

In [62]:
dropdown_value = dropdown.value
if dropdown_value == "Chicago":    
    selected_data_frame = pd.read_csv('chicago.csv')
elif dropdown_value == "New york city":
    selected_data_frame = pd.read_csv('new_york_city.csv')
elif dropdown_value == "Washington":
    selected_data_frame = pd.read_csv('washington.csv') 

selected_data_frame    
    


Unnamed: 0           Start Time             End Time  Trip Duration  \
0          5688089  2017-06-11 14:55:05  2017-06-11 15:08:21            795   
1          4096714  2017-05-11 15:30:11  2017-05-11 15:41:43            692   
2          2173887  2017-03-29 13:26:26  2017-03-29 13:48:31           1325   
3          3945638  2017-05-08 19:47:18  2017-05-08 19:59:01            703   
4          6208972  2017-06-21 07:49:16  2017-06-21 07:54:46            329   
...            ...                  ...                  ...            ...   
299995     3273600  2017-04-24 17:51:12  2017-04-24 17:59:28            495   
299996     3418509  2017-04-28 12:02:29  2017-04-28 12:19:04            994   
299997     5034995  2017-05-31 09:11:10  2017-05-31 09:24:16            785   
299998       78227  2017-01-05 08:31:37  2017-01-05 08:51:01           1164   
299999     2554332  2017-04-09 17:46:51  2017-04-09 18:06:40           1189   

                  Start Station               End Station   User Type  Gender  \
0       Suffolk St & Stanton St    W Broadway & Spring St  Subscriber    Male   
1       Lexington Ave & E 63 St           1 Ave & E 78 St  Subscriber    Male   
2             1 Pl & Clinton St      Henry St & Degraw St  Subscriber    Male   
3         Barrow St & Hudson St           W 20 St & 8 Ave  Subscriber  Female   
4               1 Ave & E 44 St           E 53 St & 3 Ave  Subscriber    Male   
...                         ...                       ...         ...     ...   
299995          W 25 St & 6 Ave           W 38 St & 8 Ave  Subscriber    Male   
299996          W 27 St & 7 Ave           W 52 St & 5 Ave  Subscriber    Male   
299997          3 Ave & E 72 St           W 44 St & 5 Ave  Subscriber    Male   
299998    Columbia St & Kane St    Barclay St & Church St  Subscriber    Male   
299999     Division St & Bowery  Lafayette St & Jersey St  Subscriber  Female   

        Birth Year  
0           1998.0  
1           1981.0  
2           1987.0  
3           1986.0  
4           1992.0  
...            ...  
299995      1977.0  
299996      1967.0  
299997      1972.0  
299998      1964.0  
299999      1985.0  

[300000 rows x 9 columns]

In [27]:
from sklearn.datasets import load_wine

wine = load_wine()
wine_data=wine.data
#alcohol_data=wine_data[: , 0]
#wine_data[:, (0, 4)]
#alcohol_data=wine.data[:, 0]
wine_data

array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]])

In [11]:
alc = wine_data[:, 0]
alc.shape

(178,)

In [7]:
less_alc_bool = alc < 13
less_alc_bool

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False,  True,  True, False,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,

In [13]:
wine_data[less_alc_bool]

array([[1.293e+01, 3.800e+00, 2.650e+00, ..., 1.030e+00, 3.520e+00,
        7.700e+02],
       [1.285e+01, 1.600e+00, 2.520e+00, ..., 1.090e+00, 3.630e+00,
        1.015e+03],
       [1.237e+01, 9.400e-01, 1.360e+00, ..., 1.050e+00, 1.820e+00,
        5.200e+02],
       ...,
       [1.282e+01, 3.370e+00, 2.300e+00, ..., 7.200e-01, 1.750e+00,
        6.850e+02],
       [1.220e+01, 3.030e+00, 2.320e+00, ..., 6.600e-01, 1.830e+00,
        5.100e+02],
       [1.277e+01, 2.390e+00, 2.280e+00, ..., 5.700e-01, 1.630e+00,
        4.700e+02]])